import type { Settings, StorageSchema } from './types';

export const DEFAULT_SETTINGS: Settings = {
  theme: 'dark',
  defaultDelay: 0,
  logEnabled: true,
  maxLogEntries: 1000,
};

export const DEFAULT_STORAGE: StorageSchema = {
  activeTabId: null,
  rules: [],
  collections: [],
  requestLog: [],
  settings: DEFAULT_SETTINGS,
  authToken: null,
  userId: null,
};

export const MESSAGE_TYPES = {
  // Tab management
  GET_ACTIVE_TABS: 'GET_ACTIVE_TABS',
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  TAB_STATUS_CHANGED: 'TAB_STATUS_CHANGED',

  // Rules
  GET_RULES: 'GET_RULES',
  CREATE_RULE: 'CREATE_RULE',
  UPDATE_RULE: 'UPDATE_RULE',
  DELETE_RULE: 'DELETE_RULE',
  TOGGLE_RULE: 'TOGGLE_RULE',
  REORDER_RULES: 'REORDER_RULES',
  RULES_UPDATED: 'RULES_UPDATED',

  // Collections
  GET_COLLECTIONS: 'GET_COLLECTIONS',
  CREATE_COLLECTION: 'CREATE_COLLECTION',
  UPDATE_COLLECTION: 'UPDATE_COLLECTION',
  DELETE_COLLECTION: 'DELETE_COLLECTION',
  TOGGLE_COLLECTION: 'TOGGLE_COLLECTION',

  // Request log
  LOG_ENTRY: 'LOG_ENTRY',
  CLEAR_LOG: 'CLEAR_LOG',

  // Content script ↔ Injected script
  INJECT_RULES: 'INJECT_RULES',
  REQUEST_INTERCEPTED: 'REQUEST_INTERCEPTED',
  REQUEST_LOGGED: 'REQUEST_LOGGED',

  // Auth
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  LOGIN_GOOGLE: 'LOGIN_GOOGLE',
  LOGIN_GITHUB: 'LOGIN_GITHUB',
  LOGOUT: 'LOGOUT',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  AUTH_STATE_CHANGED: 'AUTH_STATE_CHANGED',

  // Sync
  PUSH_TO_CLOUD: 'PUSH_TO_CLOUD',
  PULL_FROM_CLOUD: 'PULL_FROM_CLOUD',
  SYNC_STATUS: 'SYNC_STATUS',

  // Teams
  CREATE_TEAM: 'CREATE_TEAM',
  GET_TEAM: 'GET_TEAM',
  GET_USER_TEAMS: 'GET_USER_TEAMS',
  DELETE_TEAM: 'DELETE_TEAM',
  INVITE_MEMBER: 'INVITE_MEMBER',
  ACCEPT_INVITE: 'ACCEPT_INVITE',
  DECLINE_INVITE: 'DECLINE_INVITE',
  GET_PENDING_INVITES: 'GET_PENDING_INVITES',
  UPDATE_MEMBER_ROLE: 'UPDATE_MEMBER_ROLE',
  REMOVE_MEMBER: 'REMOVE_MEMBER',

  // Cloud sync
  PUSH_COLLECTION: 'PUSH_COLLECTION',
  PULL_COLLECTION: 'PULL_COLLECTION',
  GET_SYNC_STATUS: 'GET_SYNC_STATUS',

  // Version history
  GET_VERSION_HISTORY: 'GET_VERSION_HISTORY',
  GET_VERSION: 'GET_VERSION',
  RESTORE_VERSION: 'RESTORE_VERSION',

  // Billing
  CREATE_CHECKOUT_SESSION: 'CREATE_CHECKOUT_SESSION',
  CREATE_CUSTOMER_PORTAL_SESSION: 'CREATE_CUSTOMER_PORTAL_SESSION',
} as const;

export const STORAGE_KEYS = {
  ACTIVE_TAB_ID: 'activeTabId',
  RULES: 'rules',
  COLLECTIONS: 'collections',
  REQUEST_LOG: 'requestLog',
  SETTINGS: 'settings',
  AUTH_TOKEN: 'authToken',
  USER_ID: 'userId',
} as const;

export const PLAN_PRICE_IDS: Record<string, string> = {
  pro: import.meta.env.VITE_STRIPE_PRO_PRICE_ID ?? '',
  team: import.meta.env.VITE_STRIPE_TEAM_PRICE_ID ?? '',
};

// Unique prefix for window.postMessage to avoid conflicts with page scripts
export const MESSAGE_PREFIX = '__REQ_INTERCEPTOR__';
